# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Profiler-Plugins-Template
version:      0.01
version_from: lib/Devel/Profiler/Plugins/Template.pm
installdirs:  site
requires:
    Devel::Profiler:               0.05
    Template:                      2.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
